#!/bin/sh
set -e

# ensure directories existence
if [ -d "storage" ]; then
    dirs="/app/public /logs /framework/cache /framework/sessions /framework/testing /framework/views"
    for dir in ${dirs}; do
        _dir=storage${dir}
        if [ ! -d ${_dir} ]; then
            mkdir -p ${_dir}
        fi
    done

    # ensure ownership
    chown -R www-data:www-data /app/storage
fi

if [ -f "artisan" ]; then
    # enable crontab if wanted
    if [ "$ENABLE_CRONJOB" ]; then
        echo Enabled CronJob
        crontab -l | { cat; echo "* * * * * cd ${PWD} && php artisan schedule:run >> /dev/null 2>&1"; } | crontab -
    fi

    # enable migration if wanted
    if [ "$ENABLE_MIGRATION" ]; then
        echo Running Migration
        (cd /app && php artisan migrate --force)
    fi
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi
exec "$@"