#!/bin/sh
set -e

# ensure directories existence
if [ -d "storage" ]; then
    dirs="/app/public /logs /framework/cache /framework/sessions /framework/testing /framework/views"
    for dir in ${dirs}; do
        _dir=storage${dir}
        if [ ! -d ${_dir} ]; then
            mkdir -p ${_dir}
        fi
    done

    # ensure ownership
    chown -R www-data:www-data /app/storage
fi

if [ "$1" = "scheduler" ]; then
    shift;
    echo Setting up crontab file
    (crontab -l | grep -qxF "php artisan schedule:run" ) || (crontab -l | { cat; echo "* * * * * cd ${PWD} && php artisan schedule:run 2>&1"; } | crontab -)
    set -- crond -d 8 -f $@
    echo Starting crond
elif [ "$1" = "queue" ]; then
    shift;
    set -- php artisan queue:work $@
    echo Starting QueueWorker
else
    if [ -f "artisan" ]; then
        # run migration if wanted
        if [ "$RUN_MIGRATION" ]; then
            echo Running Migration
            (cd /app && php artisan migrate --force)
        fi
    fi

    # first arg is `-f` or `--some-option`
    if [ "${1#-}" != "$1" ]; then
        set -- php-fpm "$@"
    fi
fi

exec "$@"